title: AndrewLynch.net
email: andrewglynch@gmail.com
description: >-
  Personal blog of Andrew Lynch, finance professional and occasional writer.
baseurl: ""
url: "https://andrewlynch.net"

permalink: /blog/:slug

header_pages:
  - essays.md
  - influences.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - convert_posts.py
  - missing_images.md
  - Gemfile
  - Gemfile.lock
  - README.md
